# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_busy',
            field=models.BooleanField(default=False, verbose_name='busy'),
        ),
    ]
