export default {
  Karachi: 'karachi',
  Shanghai: 'shanghai',
  Beijing: 'beijing',
  Delhi: 'delhi',
  Lagos: 'lagos',
  Dhaka: 'dhaka',
  Guangzhou: 'guangzhou',
  Istanbul: 'istanbul',
  Tokyo: 'tokyo',
  Mumbai: 'mumbai',
  Moscow: 'moscow',
  'São Paulo': 'sao paulo',
  Shenzhen: 'shenzhen',
  Suzhou: 'suzhou',
  Lahore: 'lahore',
  Cairo: 'cairo',
  Kinshasa: 'kinshasa',
  Jakarta: 'jakarta',
  Seoul: 'seoul',
  'Mexico City': 'mexico city',
  Lima: 'lima',
  "Xi'an": 'xian',
  London: 'london',
  'New York City': 'new york city',
  Bengaluru: 'bengaluru',
  Bangkok: 'bangkok',
  Nanjing: 'nanjing',
  Dongguan: 'dongguan',
  Chongqing: 'chongqing',
  Tehran: 'tehran',
  Quanzhou: 'quanzhou',
  Shenyang: 'shenyang',
  Bogotá: 'bogotá',
  Hyderabad: 'hyderabad',
  'Ho Chi Minh City': 'ho chi minh city',
  'Hong Kong': 'hong kong',
  Baghdad: 'baghdad',
  Fuzhou: 'fuzhou',
  Chennai: 'chennai',
  Changsha: 'changsha',
  Wuhan: 'wuhan',
  Tianjin: 'tianjin',
  Hanoi: 'hanoi',
  Faisalabad: 'faisalabad',
  'Rio de Janeiro': 'rio de janeiro',
  Qingdao: 'qingdao',
  Foshan: 'foshan',
  Zunyi: 'zunyi',
  Santiago: 'santiago',
  Riyadh: 'riyadh',
  Ahmedabad: 'ahmedabad',
  Singapore: 'singapore',
  Shantou: 'shantou',
  Ankara: 'ankara',
  Yangon: 'yangon',
  'Saint Petersburg': 'saint petersburg',
  Casablanca: 'casablanca',
  Abidjan: 'abidjan',
  Chengdu: 'chengdu',
  Alexandria: 'alexandria',
  Kolkata: 'kolkata',
  Surat: 'surat',
  Johannesburg: 'johannesburg',
  'Dar es Salaam': 'dar es salaam',
  Shijiazhuang: 'shijiazhuang',
  Harbin: 'harbin',
  Giza: 'giza',
  İzmir: 'i̇zmir',
  Zhengzhou: 'zhengzhou',
  'New Taipei City': 'new taipei city',
  'Los Angeles': 'los angeles',
  Changchun: 'changchun',
  'Cape Town': 'cape town',
  Yokohama: 'yokohama',
  Khartoum: 'khartoum',
  Guayaquil: 'guayaquil',
  Hangzhou: 'hangzhou',
  Xiamen: 'xiamen',
  Berlin: 'berlin',
  Busan: 'busan',
  Ningbo: 'ningbo',
  Jeddah: 'jeddah',
  Durban: 'durban',
  Algiers: 'algiers',
  Kabul: 'kabul',
  Hefei: 'hefei',
  Mashhad: 'mashhad',
  Pyongyang: 'pyongyang',
  Madrid: 'madrid',
  Baku: 'baku',
  Peshawar: 'peshawar',
  Rawalpindi: 'rawalpindi',
  Tangshan: 'tangshan',
  Ekurhuleni: 'ekurhuleni',
  Nairobi: 'nairobi',
  Zhongshan: 'zhongshan',
  Multan: 'multan',
  Pune: 'pune',
  'Addis Ababa': 'addis ababa',
  Jaipur: 'jaipur',
  'Buenos Aires': 'buenos aires',
  Wenzhou: 'wenzhou',
  Incheon: 'incheon',
  'Quezon City': 'quezon city',
  Kiyv: 'kiyv',
  Salvador: 'salvador',
  Rome: 'rome',
  Luanda: 'luanda',
  Lucknow: 'lucknow',
  Kaohsiung: 'kaohsiung',
  Kanpur: 'kanpur',
  Surabaya: 'surabaya',
  Taichung: 'taichung',
  Basra: 'basra',
  Toronto: 'toronto',
  Taipei: 'taipei',
  Gujranwala: 'gujranwala',
  Chicago: 'chicago',
  Osaka: 'osaka',
  Quito: 'quito',
  Chaozhou: 'chaozhou',
  Dubai: 'dubai',
  Fortaleza: 'fortaleza',
  Chittagong: 'chittagong',
  Bandung: 'bandung',
  Managua: 'managua',
  Brasília: 'brasília',
  'Belo Horizonte': 'belo horizonte',
  Daegu: 'daegu',
  Houston: 'houston',
  Douala: 'douala',
  Medellin: 'medellin',
  Yaoundé: 'yaoundé',
  Nagpur: 'nagpur',
  Cali: 'cali',
  Tashkent: 'tashkent',
  Nagoya: 'nagoya',
  Isfahan: 'isfahan',
  'Phnom Penh': 'phnom penh',
  Kochi: 'kochi',
  Paris: 'paris',
  Ouagadougou: 'ouagadougou',
  Lanzhou: 'lanzhou',
  Kano: 'kano',
  Dalian: 'dalian',
  'Guatemala City': 'guatemala city',
  Havana: 'havana',
  Medan: 'medan',
  Accra: 'accra',
  Visakhapatnam: 'visakhapatnam',
  Jinan: 'jinan',
  Karaj: 'karaj',
  Minsk: 'minsk',
  Caracas: 'caracas',
  "Sana'a": "sana'a",
  Sapporo: 'sapporo',
  Islamabad: 'islamabad',
  Tainan: 'tainan',
  Bucharest: 'bucharest',
  Curitiba: 'curitiba',
  Shiraz: 'shiraz',
  Vienna: 'vienna',
  Brazzaville: 'brazzaville',
  Bhopal: 'bhopal',
  Hamburg: 'hamburg',
  Manila: 'manila',
  'Kuala Lumpur': 'kuala lumpur',
  Maputo: 'maputo',
  Budapest: 'budapest',
  Warsaw: 'warsaw',
  Lusaka: 'lusaka',
  Tabriz: 'tabriz',
  Palembang: 'palembang',
  Almaty: 'almaty',
  Tijuana: 'tijuana',
  Patna: 'patna',
  Montreal: 'montreal',
  'Davao City': 'davao city',
  Harare: 'harare',
  Barcelona: 'barcelona',
  Maracaibo: 'maracaibo',
  Caloocan: 'caloocan',
  Philadelphia: 'philadelphia',
  Novosibirsk: 'novosibirsk',
  Phoenix: 'phoenix',
  Oran: 'oran',
  Semarang: 'semarang',
  Recife: 'recife',
  Kobe: 'kobe',
  Daejeon: 'daejeon',
  Kampala: 'kampala',
  Kawasaki: 'kawasaki',
  Guadalajara: 'guadalajara',
  Auckland: 'auckland',
  Vijayawada: 'vijayawada',
  Fukuoka: 'fukuoka',
  Kwangju: 'kwangju',
  'Porto Alegre': 'porto alegre',
  Kyoto: 'kyoto',
  'San Antonio': 'san antonio',
  'Santa Cruz de la Sierra': 'santa cruz de la sierra',
  Munich: 'munich',
  Kharkov: 'kharkov',
  Yekaterinburg: 'yekaterinburg',
  'San Diego': 'san diego',
  Barranquilla: 'barranquilla',
  Milan: 'milan',
  Ibadan: 'ibadan',
  Makassar: 'makassar',
  Córdoba: 'córdoba',
  Prague: 'prague',
  Mandalay: 'mandalay',
  Dallas: 'dallas',
  Montevideo: 'montevideo',
  'Nizhny Novgorod': 'nizhny novgorod',
  Abuja: 'abuja',
  Calgary: 'calgary',
  Saitama: 'saitama',
  Hiroshima: 'hiroshima',
  Rosario: 'rosario',
  Brisbane: 'brisbane',
  Belgrade: 'belgrade',
  Campinas: 'campinas',
  Ulsan: 'ulsan',
  Omsk: 'omsk',
  Dakar: 'dakar',
  'Abu Dhabi': 'abu dhabi',
  Monterrey: 'monterrey',
  Tripoli: 'tripoli',
  'Rostov-on-Don': 'rostov-on-don',
  "T'bilisi": "t'bilisi",
  Fez: 'fez',
  Birmingham: 'birmingham',
  Yerevan: 'yerevan',
  Cologne: 'cologne',
  Tunis: 'tunis',
};
